##############################################################
#
# Example Secret Scanning file
#
##############################################################
#
# Learn about excluding folders and files from secret scanning: 
# https://docs.github.com/en/code-security/secret-scanning/using-advanced-secret-scanning-and-push-protection-features/excluding-folders-and-files-from-secret-scanning
#

paths-ignore:
    - 'README.md'
    - 'docs/*'