name: Cats 😺

on: [pull_request]

jobs:
  cats:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Action Cats
        uses: ruairidhwm/action-cats@1.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
